#!/bin/bash
#
# Build a .rpm package for xnec2c inside a Fedora/openSUSE container.
#
# Usage: build-rpm.sh
#
# Expects the source tree to be mounted at /build/xnec2c.
# Produces a .rpm in /build/xnec2c/artifacts/.
#
set -euo pipefail

SRC=/build/xnec2c
OUT="$SRC/artifacts"
mkdir -p "$OUT"

cd "$SRC"

# Allow git operations in the mounted source tree (dubious ownership in containers).
if command -v git >/dev/null 2>&1; then
    git config --global --add safe.directory "$SRC" 2>/dev/null || true
fi

# Determine version from git describe or AC_INIT.
if command -v git >/dev/null 2>&1 && git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    GIT_COUNT=$(git rev-list --count HEAD 2>/dev/null || echo 0)
    GIT_SHORT=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
    AC_VER=$(grep -m1 'AC_INIT' configure.ac | sed 's/.*\[\([0-9.]*\)\].*/\1/')
    VERSION="${AC_VER}.r${GIT_COUNT}.g${GIT_SHORT}"
else
    VERSION=$(grep -m1 'AC_INIT' configure.ac | sed 's/.*\[\([0-9.]*\)\].*/\1/')
fi

# Detect distro for the .rpm filename.
DISTRO=$(grep -m1 '^ID=' /etc/os-release | cut -d= -f2 | tr -d '"')
ARCH=$(rpm --eval '%{_arch}')

# RPM Release field cannot contain hyphens; sanitize the distro tag.
DISTRO_TAG="${DISTRO//-/_}"

PKG_NAME="xnec2c"
RPM_NAME="${PKG_NAME}-${VERSION}-1.${ARCH}.${DISTRO}.rpm"

echo "=== Building $RPM_NAME ==="

# Build the source.
./autogen.sh
./configure --prefix=/usr
make -j"$(nproc)"

# Install into a staging directory.
STAGE="$SRC/stage"
rm -rf "$STAGE"
mkdir -p "$STAGE"
make DESTDIR="$STAGE" install

# Build the .rpm using rpmbuild with a generated spec file.
# Create the RPM build tree.
RPM_TOP="$SRC/rpmbuild"
rm -rf "$RPM_TOP"
mkdir -p "$RPM_TOP"/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

# Generate a spec file.
cat > "$RPM_TOP/SPECS/xnec2c.spec" << EOF
Name:           ${PKG_NAME}
Version:        ${VERSION}
Release:        1.${DISTRO_TAG}
Summary:        A multi-threaded EM tool to model antenna near- and far-field radiation patterns.

License:        GPLv2+
URL:            https://github.com/9M2PJU/xnec2c
Source0:        xnec2c-${VERSION}.tar.gz
BuildRequires:  autoconf
BuildRequires:  automake
BuildRequires:  gcc
BuildRequires:  gettext-devel
BuildRequires:  glib2-devel
BuildRequires:  gtk3-devel
BuildRequires:  gsl-devel
BuildRequires:  libepoxy-devel
BuildRequires:  libtool
BuildRequires:  make
BuildRequires:  mesa-libGL-devel
BuildRequires:  pkgconf-pkg-config

# Disable debuginfo subpackages (auto-generated by Fedora's brp scripts).
%define debug_package %{nil}
%define __debug_install_post %{nil}

Requires:       gtk3
Requires:       gsl
Requires:       libepoxy
Requires:       mesa-libGL

%description
Xnec2c is a high-performance multi-threaded electromagnetic simulation
package to model antenna near- and far-field radiation patterns for
Linux and UNIX operating systems. The original FORTRAN version of NEC2
was ported to C by Neoklis Kyriazis, 5B4AZ and released as nec2c. Later
he wrote xnec2c, a graphical interface for ease of use with many more
features:
    Multi-threading operation on SMP machines
    On-demand Calculation
    Built-in NEC2 input file editor
    Accelerated Linear Algebra Support
    Interactive Operation
    User Interface
    Color Coding
    and much more.

%prep
%setup -q

%build
./autogen.sh
%configure
%make_build

%install
%make_install

# Remove symlink that may cause rpm conflicts.
rm -f %{buildroot}%{_datadir}/%{name}/doc

%post
update-mime-database %{_datadir}/mime &>/dev/null || :
update-desktop-database &>/dev/null || :
gtk-update-icon-cache %{_datadir}/icons/hicolor &>/dev/null || :

%postun
update-mime-database %{_datadir}/mime &>/dev/null || :
update-desktop-database &>/dev/null || :
gtk-update-icon-cache %{_datadir}/icons/hicolor &>/dev/null || :

%files
%license COPYING
%doc %{_datadir}/doc/%{name}
%{_bindir}/%{name}
%{_datadir}/%{name}/
%{_datadir}/applications/%{name}.desktop
%{_datadir}/mime/packages/x-nec2.xml
%{_datadir}/icons/hicolor/256x256/apps/%{name}.png
%{_datadir}/pixmaps/%{name}.svg
%{_mandir}/man1/%{name}.1*
%{_datadir}/locale/*/LC_MESSAGES/%{name}.mo

%changelog
* Thu Jul 23 2026 9M2PJU <9m2pju@hamradio.my> - ${VERSION}-1
- Automated build from GitHub Actions.
EOF

# Create a source tarball from the current tree.
TARBALL="$RPM_TOP/SOURCES/xnec2c-${VERSION}.tar.gz"
tar -czf "$TARBALL" \
    --transform "s,^,xnec2c-${VERSION}/," \
    --exclude='.git' \
    --exclude='artifacts' \
    --exclude='stage' \
    --exclude='rpmbuild' \
    .

# Build the RPM.  --nodeps skips BuildRequires resolution since deps are
# installed manually by the caller (package names differ across distros).
rpmbuild -bb \
    --nodeps \
    --define "_topdir $RPM_TOP" \
    --define "dist .${DISTRO}" \
    --target "$ARCH" \
    "$RPM_TOP/SPECS/xnec2c.spec"

# Copy the built RPM to the output directory with our naming convention.
BUILT_RPM=$(find "$RPM_TOP/RPMS" -name "xnec2c-*.rpm" -type f | head -1)
if [ -z "$BUILT_RPM" ]; then
    echo "ERROR: No RPM was built" >&2
    exit 1
fi
cp "$BUILT_RPM" "$OUT/$RPM_NAME"

echo "=== Built: $OUT/$RPM_NAME ==="
ls -la "$OUT/$RPM_NAME"
